<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeederDat extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countrys = array(
            [4, 'AF', 'AFG', 'Afganistán'],
            [248, 'AX', 'ALA', 'Islas Gland'],
            [8, 'AL', 'ALB', 'Albania'],
            [276, 'DE', 'DEU', 'Alemania'],
            [20, 'AD', 'AND', 'Andorra'],
            [24, 'AO', 'AGO', 'Angola'],
            [660, 'AI', 'AIA', 'Anguilla'],
            [10, 'AQ', 'ATA', 'Antártida'],
            [28, 'AG', 'ATG', 'Antigua y Barbuda'],
            [530, 'AN', 'ANT', 'Antillas Holandesas'],
            [682, 'SA', 'SAU', 'Arabia Saudí'],
            [12, 'DZ', 'DZA', 'Argelia'],
            [32, 'AR', 'ARG', 'Argentina'],
            [51, 'AM', 'ARM', 'Armenia'],
            [533, 'AW', 'ABW', 'Aruba'],
            [36, 'AU', 'AUS', 'Australia'],
            [40, 'AT', 'AUT', 'Austria'],
            [31, 'AZ', 'AZE', 'Azerbaiyán'],
            [44, 'BS', 'BHS', 'Bahamas'],
            [48, 'BH', 'BHR', 'Bahréin'],
            [50, 'BD', 'BGD', 'Bangladesh'],
            [52, 'BB', 'BRB', 'Barbados'],
            [112, 'BY', 'BLR', 'Bielorrusia'],
            [56, 'BE', 'BEL', 'Bélgica'],
            [84, 'BZ', 'BLZ', 'Belice'],
            [204, 'BJ', 'BEN', 'Benin'],
            [60, 'BM', 'BMU', 'Bermudas'],
            [64, 'BT', 'BTN', 'Bhután'],
            [68, 'BO', 'BOL', 'Bolivia'],
            [70, 'BA', 'BIH', 'Bosnia y Herzegovina'],
            [72, 'BW', 'BWA', 'Botsuana'],
            [74, 'BV', 'BVT', 'Isla Bouvet'],
            [76, 'BR', 'BRA', 'Brasil'],
            [96, 'BN', 'BRN', 'Brunéi'],
            [100, 'BG', 'BGR', 'Bulgaria'],
            [854, 'BF', 'BFA', 'Burkina Faso'],
            [108, 'BI', 'BDI', 'Burundi'],
            [132, 'CV', 'CPV', 'Cabo Verde'],
            [136, 'KY', 'CYM', 'Islas Caimán'],
            [116, 'KH', 'KHM', 'Camboya'],
            [120, 'CM', 'CMR', 'Camerún'],
            [124, 'CA', 'CAN', 'Canadá'],
            [140, 'CF', 'CAF', 'República Centroafricana'],
            [148, 'TD', 'TCD', 'Chad'],
            [203, 'CZ', 'CZE', 'República Checa'],
            [152, 'CL', 'CHL', 'Chile'],
            [156, 'CN', 'CHN', 'China'],
            [196, 'CY', 'CYP', 'Chipre'],
            [162, 'CX', 'CXR', 'Isla de Navidad'],
            [336, 'VA', 'VAT', 'Ciudad del Vaticano'],
            [166, 'CC', 'CCK', 'Islas Cocos'],
            [170, 'CO', 'COL', 'Colombia'],
            [174, 'KM', 'COM', 'Comoras'],
            [180, 'CD', 'COD', 'República Democrática del Congo'],
            [178, 'CG', 'COG', 'Congo'],
            [184, 'CK', 'COK', 'Islas Cook'],
            [408, 'KP', 'PRK', 'Corea del Norte'],
            [410, 'KR', 'KOR', 'Corea del Sur'],
            [384, 'CI', 'CIV', 'Costa de Marfil'],
            [188, 'CR', 'CRI', 'Costa Rica'],
            [191, 'HR', 'HRV', 'Croacia'],
            [192, 'CU', 'CUB', 'Cuba'],
            [208, 'DK', 'DNK', 'Dinamarca'],
            [212, 'DM', 'DMA', 'Dominica'],
            [214, 'DO', 'DOM', 'República Dominicana'],
            [218, 'EC', 'ECU', 'Ecuador'],
            [818, 'EG', 'EGY', 'Egipto'],
            [222, 'SV', 'SLV', 'El Salvador'],
            [784, 'AE', 'ARE', 'Emiratos Árabes Unidos'],
            [232, 'ER', 'ERI', 'Eritrea'],
            [703, 'SK', 'SVK', 'Eslovaquia'],
            [705, 'SI', 'SVN', 'Eslovenia'],
            [724, 'ES', 'ESP', 'España'],
            [581, 'UM', 'UMI', 'Islas ultramarinas de Estados Unidos'],
            [840, 'US', 'USA', 'Estados Unidos'],
            [233, 'EE', 'EST', 'Estonia'],
            [231, 'ET', 'ETH', 'Etiopía'],
            [234, 'FO', 'FRO', 'Islas Feroe'],
            [608, 'PH', 'PHL', 'Filipinas'],
            [246, 'FI', 'FIN', 'Finlandia'],
            [242, 'FJ', 'FJI', 'Fiyi'],
            [250, 'FR', 'FRA', 'Francia'],
            [266, 'GA', 'GAB', 'Gabón'],
            [270, 'GM', 'GMB', 'Gambia'],
            [268, 'GE', 'GEO', 'Georgia'],
            [239, 'GS', 'SGS', 'Islas Georgias del Sur y Sandwich del Sur'],
            [288, 'GH', 'GHA', 'Ghana'],
            [292, 'GI', 'GIB', 'Gibraltar'],
            [308, 'GD', 'GRD', 'Granada'],
            [300, 'GR', 'GRC', 'Grecia'],
            [304, 'GL', 'GRL', 'Groenlandia'],
            [312, 'GP', 'GLP', 'Guadalupe'],
            [316, 'GU', 'GUM', 'Guam'],
            [320, 'GT', 'GTM', 'Guatemala'],
            [254, 'GF', 'GUF', 'Guayana Francesa'],
            [324, 'GN', 'GIN', 'Guinea'],
            [226, 'GQ', 'GNQ', 'Guinea Ecuatorial'],
            [624, 'GW', 'GNB', 'Guinea-Bissau'],
            [328, 'GY', 'GUY', 'Guyana'],
            [332, 'HT', 'HTI', 'Haití'],
            [334, 'HM', 'HMD', 'Islas Heard y McDonald'],
            [340, 'HN', 'HND', 'Honduras'],
            [344, 'HK', 'HKG', 'Hong Kong'],
            [348, 'HU', 'HUN', 'Hungría'],
            [356, 'IN', 'IND', 'India'],
            [360, 'ID', 'IDN', 'Indonesia'],
            [364, 'IR', 'IRN', 'Irán'],
            [368, 'IQ', 'IRQ', 'Iraq'],
            [372, 'IE', 'IRL', 'Irlanda'],
            [352, 'IS', 'ISL', 'Islandia'],
            [376, 'IL', 'ISR', 'Israel'],
            [380, 'IT', 'ITA', 'Italia'],
            [388, 'JM', 'JAM', 'Jamaica'],
            [392, 'JP', 'JPN', 'Japón'],
            [400, 'JO', 'JOR', 'Jordania'],
            [398, 'KZ', 'KAZ', 'Kazajstán'],
            [404, 'KE', 'KEN', 'Kenia'],
            [417, 'KG', 'KGZ', 'Kirguistán'],
            [296, 'KI', 'KIR', 'Kiribati'],
            [414, 'KW', 'KWT', 'Kuwait'],
            [418, 'LA', 'LAO', 'Laos'],
            [426, 'LS', 'LSO', 'Lesotho'],
            [428, 'LV', 'LVA', 'Letonia'],
            [422, 'LB', 'LBN', 'Líbano'],
            [430, 'LR', 'LBR', 'Liberia'],
            [434, 'LY', 'LBY', 'Libia'],
            [438, 'LI', 'LIE', 'Liechtenstein'],
            [440, 'LT', 'LTU', 'Lituania'],
            [442, 'LU', 'LUX', 'Luxemburgo'],
            [446, 'MO', 'MAC', 'Macao'],
            [807, 'MK', 'MKD', 'ARY Macedonia'],
            [450, 'MG', 'MDG', 'Madagascar'],
            [458, 'MY', 'MYS', 'Malasia'],
            [454, 'MW', 'MWI', 'Malawi'],
            [462, 'MV', 'MDV', 'Maldivas'],
            [466, 'ML', 'MLI', 'Malí'],
            [470, 'MT', 'MLT', 'Malta'],
            [238, 'FK', 'FLK', 'Islas Malvinas'],
            [580, 'MP', 'MNP', 'Islas Marianas del Norte'],
            [504, 'MA', 'MAR', 'Marruecos'],
            [584, 'MH', 'MHL', 'Islas Marshall'],
            [474, 'MQ', 'MTQ', 'Martinica'],
            [480, 'MU', 'MUS', 'Mauricio'],
            [478, 'MR', 'MRT', 'Mauritania'],
            [175, 'YT', 'MYT', 'Mayotte'],
            [484, 'MX', 'MEX', 'México'],
            [583, 'FM', 'FSM', 'Micronesia'],
            [498, 'MD', 'MDA', 'Moldavia'],
            [492, 'MC', 'MCO', 'Mónaco'],
            [496, 'MN', 'MNG', 'Mongolia'],
            [500, 'MS', 'MSR', 'Montserrat'],
            [508, 'MZ', 'MOZ', 'Mozambique'],
            [104, 'MM', 'MMR', 'Myanmar'],
            [516, 'NA', 'NAM', 'Namibia'],
            [520, 'NR', 'NRU', 'Nauru'],
            [524, 'NP', 'NPL', 'Nepal'],
            [558, 'NI', 'NIC', 'Nicaragua'],
            [562, 'NE', 'NER', 'Níger'],
            [566, 'NG', 'NGA', 'Nigeria'],
            [570, 'NU', 'NIU', 'Niue'],
            [574, 'NF', 'NFK', 'Isla Norfolk'],
            [578, 'NO', 'NOR', 'Noruega'],
            [540, 'NC', 'NCL', 'Nueva Caledonia'],
            [554, 'NZ', 'NZL', 'Nueva Zelanda'],
            [512, 'OM', 'OMN', 'Omán'],
            [528, 'NL', 'NLD', 'Países Bajos'],
            [586, 'PK', 'PAK', 'Pakistán'],
            [585, 'PW', 'PLW', 'Palau'],
            [275, 'PS', 'PSE', 'Palestina'],
            [591, 'PA', 'PAN', 'Panamá'],
            [598, 'PG', 'PNG', 'Papúa Nueva Guinea'],
            [600, 'PY', 'PRY', 'Paraguay'],
            [604, 'PE', 'PER', 'Perú'],
            [612, 'PN', 'PCN', 'Islas Pitcairn'],
            [258, 'PF', 'PYF', 'Polinesia Francesa'],
            [616, 'PL', 'POL', 'Polonia'],
            [620, 'PT', 'PRT', 'Portugal'],
            [630, 'PR', 'PRI', 'Puerto Rico'],
            [634, 'QA', 'QAT', 'Qatar'],
            [826, 'GB', 'GBR', 'Reino Unido'],
            [638, 'RE', 'REU', 'Reunión'],
            [646, 'RW', 'RWA', 'Ruanda'],
            [642, 'RO', 'ROU', 'Rumania'],
            [643, 'RU', 'RUS', 'Rusia'],
            [732, 'EH', 'ESH', 'Sahara Occidental'],
            [90, 'SB', 'SLB', 'Islas Salomón'],
            [882, 'WS', 'WSM', 'Samoa'],
            [16, 'AS', 'ASM', 'Samoa Americana'],
            [659, 'KN', 'KNA', 'San Cristóbal y Nevis'],
            [674, 'SM', 'SMR', 'San Marino'],
            [666, 'PM', 'SPM', 'San Pedro y Miquelón'],
            [670, 'VC', 'VCT', 'San Vicente y las Granadinas'],
            [654, 'SH', 'SHN', 'Santa Helena'],
            [662, 'LC', 'LCA', 'Santa Lucía'],
            [678, 'ST', 'STP', 'Santo Tomé y Príncipe'],
            [686, 'SN', 'SEN', 'Senegal'],
            [891, 'CS', 'SCG', 'Serbia y Montenegro'],
            [690, 'SC', 'SYC', 'Seychelles'],
            [694, 'SL', 'SLE', 'Sierra Leona'],
            [702, 'SG', 'SGP', 'Singapur'],
            [760, 'SY', 'SYR', 'Siria'],
            [706, 'SO', 'SOM', 'Somalia'],
            [144, 'LK', 'LKA', 'Sri Lanka'],
            [748, 'SZ', 'SWZ', 'Suazilandia'],
            [710, 'ZA', 'ZAF', 'Sudáfrica'],
            [736, 'SD', 'SDN', 'Sudán'],
            [752, 'SE', 'SWE', 'Suecia'],
            [756, 'CH', 'CHE', 'Suiza'],
            [740, 'SR', 'SUR', 'Surinam'],
            [744, 'SJ', 'SJM', 'Svalbard y Jan Mayen'],
            [764, 'TH', 'THA', 'Tailandia'],
            [158, 'TW', 'TWN', 'Taiwán'],
            [834, 'TZ', 'TZA', 'Tanzania'],
            [762, 'TJ', 'TJK', 'Tayikistán'],
            [86, 'IO', 'IOT', 'Territorio Británico del Océano Índico'],
            [260, 'TF', 'ATF', 'Territorios Australes Franceses'],
            [626, 'TL', 'TLS', 'Timor Oriental'],
            [768, 'TG', 'TGO', 'Togo'],
            [772, 'TK', 'TKL', 'Tokelau'],
            [776, 'TO', 'TON', 'Tonga'],
            [780, 'TT', 'TTO', 'Trinidad y Tobago'],
            [788, 'TN', 'TUN', 'Túnez'],
            [796, 'TC', 'TCA', 'Islas Turcas y Caicos'],
            [795, 'TM', 'TKM', 'Turkmenistán'],
            [792, 'TR', 'TUR', 'Turquía'],
            [798, 'TV', 'TUV', 'Tuvalu'],
            [804, 'UA', 'UKR', 'Ucrania'],
            [800, 'UG', 'UGA', 'Uganda'],
            [858, 'UY', 'URY', 'Uruguay'],
            [860, 'UZ', 'UZB', 'Uzbekistán'],
            [548, 'VU', 'VUT', 'Vanuatu'],
            [862, 'VE', 'VEN', 'Venezuela'],
            [704, 'VN', 'VNM', 'Vietnam'],
            [92, 'VG', 'VGB', 'Islas Vírgenes Británicas'],
            [850, 'VI', 'VIR', 'Islas Vírgenes de los Estados Unidos'],
            [876, 'WF', 'WLF', 'Wallis y Futuna'],
            [887, 'YE', 'YEM', 'Yemen'],
            [262, 'DJ', 'DJI', 'Yibuti'],
            [894, 'ZM', 'ZMB', 'Zambia'],
            [716, 'ZW', 'ZWE', 'Zimbabue'],
        );

        foreach($countrys as $country){
            Country::firstOrCreate([
                'code'=>$country[0],
                'iso1'=>$country[1],
                'iso2'=>$country[2],
                'name'=>$country[3],
            ]);
        }
    }
}
